name: devstore

services:
    
    database:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: devstore-mssql
        ports:
            - "1433:1433"
        expose:
            - 1433
        environment:
            SA_PASSWORD: "MyDB@123"
            ACCEPT_EULA: "Y"
        healthcheck:
            test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P MyDB@123 -Q 'SELECT 1'" ]
            interval: 3s
            timeout: 5s
            retries: 10
            start_period: 5s            
    
    rabbitmq:
        image: rabbitmq:4.1
        container_name: devstore-rabbit
        hostname: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        expose:
            - 5672
            - 15672
        environment:
            RABBITMQ_DEFAULT_USER: "devstore"
            RABBITMQ_DEFAULT_PASS: "devstore"
        healthcheck: # Add health check to ensure RabbitMQ is ready
            test: [ "CMD", "rabbitmqctl", "status" ]
            interval: 3s
            timeout: 5s
            retries: 10
            start_period: 5s
    
    logging:
        image: datalust/seq:2025.1
        container_name: devstore-seq
        ports:
            - 5341:80
        environment:
            ACCEPT_EULA: "Y"
            SEQ_FIRSTRUN_ADMINPASSWORD: "MyAdminPassword"
        healthcheck:
            test: "/seqsvr/Client/seqcli node health -s http://localhost"
            interval: 3s
            timeout: 5s
            retries: 10
            start_period: 5s    
    
    generate-pfx:
        image: emberstack/openssl:latest # last update October 2019
        container_name: generate-pfx
        volumes:
            - ./certs:/https:rw
            - nginx-certs:/nginx-certs:rw
        command: >
            sh -c "(
                   rm -f /https/devstore.academy-localhost.pfx &&
                   openssl genrsa -out devstore.rsa 2048 &&
                   openssl req -sha256 -new -key devstore.rsa -out devstore.csr -subj '/CN=localhost' &&
                   openssl x509 -req -sha256 -days 365 -in devstore.csr -signkey devstore.rsa -out devstore.crt &&
                   openssl pkcs12 -export -out /https/devstore.academy-localhost.pfx -inkey devstore.rsa -in devstore.crt -password pass:9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe &&
                   rm devstore.rsa devstore.csr devstore.crt)"           

    devstore-server:        
        image: nginx:1.29
        container_name: devstore-server 
        restart: always
        volumes:
            - ./nginx/devstore.conf:/etc/nginx/conf.d/default.conf:ro
            - nginx-certs:/etc/nginx/certs:ro
        ports:
            - "7500:80"
            - "7501:443"
            - "7510:8080"
            - "7511:4443"
        depends_on:
            generate-pfx:
                condition: service_completed_successfully

volumes:
    dpkeys:
    nginx-certs:
