name: devstore

x-common-variables: &common-variables
    ASPNETCORE_ENVIRONMENT: Docker
    ASPNETCORE_URLS: https://+:443;http://+:80
    ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
    ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
    AppSettings__DatabaseType: SqlServer
    MessageQueueConnection__MessageBus: host=rabbitmq:5672;publisherConfirms=true;timeout=30;username=devstore;password=devstore

include:
    - docker-common-resources.yml

services:
    
    api-identity:
        image: devstore-api-identity:preview
        container_name: devstore-api-identity
        build:
            context: ../src
            dockerfile: ./services/DevStore.Identity.API/Dockerfile        
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=database;Database=LocalDSUsers;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
        volumes:
            - ./certs:/https:ro
        depends_on:
            generate-pfx:
                condition: service_completed_successfully
            database:
                condition: service_healthy
            logging:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy

    api-cart:
        image: devstore-api-cart:preview
        container_name: devstore-api-cart
        build:
            context: ../src
            dockerfile: ./services/DevStore.ShoppingCart.API/Dockerfile
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=database;Database=LocalDSShoppingCart;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
        volumes:
            - ./certs:/https:ro
        depends_on:
            api-identity:
                condition: service_started

    api-catalog:
        image: devstore-api-catalog:preview
        container_name: devstore-api-catalog
        build:
            context: ../src
            dockerfile: ./services/DevStore.Catalog.API/Dockerfile
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=database;Database=LocalDSCatalog;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
        volumes:
            - ./certs:/https:ro
        depends_on:
            api-identity:
                condition: service_started

    api-customers:
        image: devstore-api-customers:preview
        container_name: devstore-api-customers
        build:
            context: ../src
            dockerfile: ./services/DevStore.Customers.API/Dockerfile
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=database;Database=LocalDSCustomers;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
        volumes:
            - ./certs:/https:ro
        depends_on:
            api-identity:
                condition: service_started

    api-order:
        image: devstore-api-order:preview
        container_name: devstore-api-order
        build:
            context: ../src
            dockerfile: ./services/DevStore.Orders.API/Dockerfile
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=database;Database=LocalDSOrders;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            Logging__Console__FormatterName: ""
        volumes:
            - ./certs:/https:ro
        depends_on:
            api-identity:
                condition: service_started

    api-billing:
        image: devstore-api-billing:preview
        container_name: devstore-api-billing
        build:
            context: ../src
            dockerfile: ./services/DevStore.Billing.API/Dockerfile
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=database;Database=LocalDSBilling;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
        volumes:
            - ./certs:/https:ro
        depends_on:
            api-identity:
                condition: service_started
            api-order:
                condition: service_started
    
    api-bff-checkout:
        image: devstore-api-bff-checkout:preview
        container_name: devstore-api-bff-checkout
        build:
            context: ../src
            dockerfile: ./api-gateways/DevStore.Bff.Checkout/Dockerfile
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=database;Database=LocalDSStatus;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
        volumes:
            - ./certs:/https:ro
        depends_on:
            - api-identity
            - api-cart
            - api-billing
            - api-order
    
    web-mvc:
        image: devstore-web-mvc-ecommerce:preview
        container_name: devstore-web-mvc-ecommerce
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=database;Database=LocalDSStatus;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            LC_ALL: "en_US.UTF-8"
            LANG: "en_US.UTF-8"
            # Change the two lines above to your culture (ex pt_BR)
            USE_HTTPS_REDIRECTION: "false"
        expose:
            - 80
            - 443
        volumes:
            - ./certs:/https:ro
            - dpkeys:/var/data_protection_keys/
        depends_on:
            - api-catalog
            - api-identity
            - api-customers
            - api-bff-checkout
    
    web-status:
        image: devstore-web-status:preview
        container_name: devstore-web-status
        build:
            context: ../src
            dockerfile: ./web/DevStore.WebApp.Status/Dockerfile
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=database;Database=LocalDSStatus;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
        volumes:
            - ./certs:/https:ro
            - ./certs/devstore.crt:/usr/local/share/ca-certificates/devstore.crt
        depends_on:
            - web-mvc

volumes:
    dpkeys:
    nginx-certs:
