name: Build devStore

on:
  push:
    paths:
      - 'global.json'
      - 'src/**'
      - '.github/**'
    branches:
      - main
  pull_request:
    paths:
      - 'global.json'
      - 'src/**'
      - '.github/**'
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-services:
    runs-on: ubuntu-latest
    name: Build docker image services   

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Tag name
        id: tagging
        run: |          
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
              echo "TAG=latest" >> $GITHUB_ENV
          else
              echo "TAG=preview" >> $GITHUB_ENV
          fi

      - name: Build docker images
        working-directory: ./docker
        env:
          TAG: ${{ steps.tagging.outputs.TAG }}
        run: |
          TAG=${{ env.TAG }} docker compose -f ./docker-compose-local.yml build

      - name: Push docker images
        working-directory: ./docker
        env:
          TAG: ${{ steps.tagging.outputs.TAG }}
        run: |
          TAG=${{ env.TAG }} docker compose -f ./docker-compose-local.yml push
